# Java Maven CircleCI 2.0 configuration file
#
#
defaults: &defaults
    working_directory: ~/gwt-uibinder
    docker:
      - image: circleci/openjdk:8-jdk
        environment: 
          _JAVA_OPTIONS: "-Xms1g -Xmx1g"


version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: environment check
          command: |
            java -XX:+PrintFlagsFinal -version | grep -iE 'HeapSize|PermSize|ThreadStackSize'
            env MAVEN_OPTS="-XX:+PrintFlagsFinal" mvn -version | grep -iE 'HeapSize|PermSize|ThreadStackSize'

      - run:
          name: build and fetch dependencies
          command: |
            if [ ! -e ~/.m2/ ]; then mkdir ~/.m2/; fi
            cat .circleci/settings.xml > ~/.m2/settings.xml
            mvn package dependency:go-offline || true

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run tests!
      - run: mvn integration-test


